#!/usr/bin/env bash
set -euo pipefail

echo "============================================"
echo " GitHub 자격증명 설정 안내"
echo "============================================"
echo ""
echo "--- 방법 1: SSH 키 (권장) ---"
echo ""
echo "1. 키 생성:"
echo "   ssh-keygen -t ed25519 -C \"your@email.com\""
echo ""
echo "2. ssh-agent 에 등록:"
echo "   eval \"\$(ssh-agent -s)\""
echo "   ssh-add ~/.ssh/id_ed25519"
echo ""
echo "3. 공개 키 복사:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   (GitHub → Settings → SSH and GPG keys → New SSH key 에 붙여넣기)"
echo ""
echo "4. 연결 테스트:"
echo "   ssh -T git@github.com"
echo ""
echo "--- 방법 2: HTTPS + PAT ---"
echo ""
echo "1. PAT 생성:"
echo "   GitHub → Settings → Developer settings"
echo "   → Personal access tokens → Tokens (classic)"
echo "   → Generate new token"
echo "   (repo 권한 체크)"
echo ""
echo "2. 자격증명 저장:"
echo "   git config --global credential.helper store"
echo "   (첫 push/pull 시 사용자명과 PAT 입력 → 저장됨)"
echo ""
echo "--- 현재 SSH 키 상태 ---"
if [ -f "$HOME/.ssh/id_ed25519.pub" ]; then
    echo "공개 키 발견:"
    cat "$HOME/.ssh/id_ed25519.pub"
elif [ -f "$HOME/.ssh/id_rsa.pub" ]; then
    echo "RSA 공개 키 발견:"
    cat "$HOME/.ssh/id_rsa.pub"
else
    echo "(SSH 공개 키 없음 — 위 1번 방법으로 생성하세요)"
fi
